export type CreateVariantPromotionWorkflowInput = {
    code: string;
    description?: string;
    type: "amount_off_products" | "percentage_off_product" | "buy_x_get_y";
    currency_code: string;
    discount_kind: "percentage" | "fixed";
    value: number;
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    variant_ids: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    apply_to_quantity?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: Date;
    ends_at?: Date;
    campaign_id?: string;
    is_automatic?: boolean;
    status?: "active" | "draft";
    is_tax_inclusive?: boolean;
    usage_limit?: number;
};
export declare const createVariantPromotionWorkflow: import("@medusajs/framework/workflows-sdk").ReturnWorkflow<CreateVariantPromotionWorkflowInput, import("@medusajs/types").PromotionDTO[], []>;
