import { z } from "zod";
export declare const RESOLVED_VARIANT_ATTRIBUTE = "items.variant.id";
export declare const CreateVariantPromotionSchema: z.ZodEffects<z.ZodObject<{
    code: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    type: z.ZodEnum<["amount_off_products", "percentage_off_product", "buy_x_get_y"]>;
    currency_code: z.ZodString;
    discount_kind: z.ZodEnum<["percentage", "fixed"]>;
    value: z.ZodNumber;
    allocation: z.ZodDefault<z.ZodOptional<z.ZodEnum<["each", "across", "once"]>>>;
    max_quantity: z.ZodOptional<z.ZodNumber>;
    variant_ids: z.ZodEffects<z.ZodArray<z.ZodString, "many">, string[], string[]>;
    buy_variant_ids: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    buy_min_quantity: z.ZodOptional<z.ZodNumber>;
    apply_to_quantity: z.ZodOptional<z.ZodNumber>;
    status: z.ZodDefault<z.ZodOptional<z.ZodEnum<["active", "draft"]>>>;
    is_tax_inclusive: z.ZodDefault<z.ZodOptional<z.ZodBoolean>>;
    usage_limit: z.ZodOptional<z.ZodNumber>;
    customer_group_ids: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    region_ids: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    starts_at: z.ZodOptional<z.ZodDate>;
    ends_at: z.ZodOptional<z.ZodDate>;
    campaign_id: z.ZodOptional<z.ZodString>;
    is_automatic: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    code?: string;
    description?: string;
    type?: "amount_off_products" | "percentage_off_product" | "buy_x_get_y";
    currency_code?: string;
    discount_kind?: "percentage" | "fixed";
    status?: "active" | "draft";
    value?: number;
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    variant_ids?: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    apply_to_quantity?: number;
    is_tax_inclusive?: boolean;
    usage_limit?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: Date;
    ends_at?: Date;
    campaign_id?: string;
    is_automatic?: boolean;
}, {
    code?: string;
    description?: string;
    type?: "amount_off_products" | "percentage_off_product" | "buy_x_get_y";
    currency_code?: string;
    discount_kind?: "percentage" | "fixed";
    status?: "active" | "draft";
    value?: number;
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    variant_ids?: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    apply_to_quantity?: number;
    is_tax_inclusive?: boolean;
    usage_limit?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: Date;
    ends_at?: Date;
    campaign_id?: string;
    is_automatic?: boolean;
}>, {
    code?: string;
    description?: string;
    type?: "amount_off_products" | "percentage_off_product" | "buy_x_get_y";
    currency_code?: string;
    discount_kind?: "percentage" | "fixed";
    status?: "active" | "draft";
    value?: number;
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    variant_ids?: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    apply_to_quantity?: number;
    is_tax_inclusive?: boolean;
    usage_limit?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: Date;
    ends_at?: Date;
    campaign_id?: string;
    is_automatic?: boolean;
}, {
    code?: string;
    description?: string;
    type?: "amount_off_products" | "percentage_off_product" | "buy_x_get_y";
    currency_code?: string;
    discount_kind?: "percentage" | "fixed";
    status?: "active" | "draft";
    value?: number;
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    variant_ids?: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    apply_to_quantity?: number;
    is_tax_inclusive?: boolean;
    usage_limit?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: Date;
    ends_at?: Date;
    campaign_id?: string;
    is_automatic?: boolean;
}>;
export type CreateVariantPromotionInput = z.infer<typeof CreateVariantPromotionSchema>;
export declare const TargetRulesBatchSchema: z.ZodEffects<z.ZodObject<{
    add: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    remove: z.ZodDefault<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
}, "strip", z.ZodTypeAny, {
    add?: string[];
    remove?: string[];
}, {
    add?: string[];
    remove?: string[];
}>, {
    add?: string[];
    remove?: string[];
}, {
    add?: string[];
    remove?: string[];
}>;
export type TargetRulesBatchInput = z.infer<typeof TargetRulesBatchSchema>;
