import { z } from "zod";
export declare const RESOLVED_VARIANT_ATTRIBUTE = "items.variant.id";
export declare const CreateVariantPromotionSchema: z.ZodEffects<z.ZodEffects<z.ZodObject<{
    code: z.ZodEffects<z.ZodString, string, string>;
    description: z.ZodOptional<z.ZodString>;
    type: z.ZodDefault<z.ZodEnum<["percentage_off_product", "buy_x_get_y"]>>;
    currency_code: z.ZodDefault<z.ZodString>;
    discount_kind: z.ZodDefault<z.ZodEnum<["percentage", "fixed"]>>;
    value: z.ZodNumber;
    allocation: z.ZodDefault<z.ZodEnum<["each", "across", "once"]>>;
    max_quantity: z.ZodOptional<z.ZodNumber>;
    status: z.ZodDefault<z.ZodEnum<["active", "draft"]>>;
    is_automatic: z.ZodDefault<z.ZodBoolean>;
    is_tax_inclusive: z.ZodDefault<z.ZodBoolean>;
    usage_limit: z.ZodOptional<z.ZodNumber>;
    customer_group_ids: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    region_ids: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    starts_at: z.ZodOptional<z.ZodString>;
    ends_at: z.ZodOptional<z.ZodString>;
    variant_ids: z.ZodArray<z.ZodString, "many">;
    buy_variant_ids: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    buy_min_quantity: z.ZodOptional<z.ZodNumber>;
    campaign_id: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    code?: string;
    status?: "active" | "draft";
    value?: number;
    type?: "percentage_off_product" | "buy_x_get_y";
    description?: string;
    currency_code?: string;
    discount_kind?: "percentage" | "fixed";
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    is_automatic?: boolean;
    is_tax_inclusive?: boolean;
    usage_limit?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: string;
    ends_at?: string;
    variant_ids?: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    campaign_id?: string;
}, {
    code?: string;
    status?: "active" | "draft";
    value?: number;
    type?: "percentage_off_product" | "buy_x_get_y";
    description?: string;
    currency_code?: string;
    discount_kind?: "percentage" | "fixed";
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    is_automatic?: boolean;
    is_tax_inclusive?: boolean;
    usage_limit?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: string;
    ends_at?: string;
    variant_ids?: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    campaign_id?: string;
}>, {
    code?: string;
    status?: "active" | "draft";
    value?: number;
    type?: "percentage_off_product" | "buy_x_get_y";
    description?: string;
    currency_code?: string;
    discount_kind?: "percentage" | "fixed";
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    is_automatic?: boolean;
    is_tax_inclusive?: boolean;
    usage_limit?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: string;
    ends_at?: string;
    variant_ids?: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    campaign_id?: string;
}, {
    code?: string;
    status?: "active" | "draft";
    value?: number;
    type?: "percentage_off_product" | "buy_x_get_y";
    description?: string;
    currency_code?: string;
    discount_kind?: "percentage" | "fixed";
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    is_automatic?: boolean;
    is_tax_inclusive?: boolean;
    usage_limit?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: string;
    ends_at?: string;
    variant_ids?: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    campaign_id?: string;
}>, {
    code?: string;
    status?: "active" | "draft";
    value?: number;
    type?: "percentage_off_product" | "buy_x_get_y";
    description?: string;
    currency_code?: string;
    discount_kind?: "percentage" | "fixed";
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    is_automatic?: boolean;
    is_tax_inclusive?: boolean;
    usage_limit?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: string;
    ends_at?: string;
    variant_ids?: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    campaign_id?: string;
}, {
    code?: string;
    status?: "active" | "draft";
    value?: number;
    type?: "percentage_off_product" | "buy_x_get_y";
    description?: string;
    currency_code?: string;
    discount_kind?: "percentage" | "fixed";
    allocation?: "each" | "across" | "once";
    max_quantity?: number;
    is_automatic?: boolean;
    is_tax_inclusive?: boolean;
    usage_limit?: number;
    customer_group_ids?: string[];
    region_ids?: string[];
    starts_at?: string;
    ends_at?: string;
    variant_ids?: string[];
    buy_variant_ids?: string[];
    buy_min_quantity?: number;
    campaign_id?: string;
}>;
export type CreateVariantPromotionInput = z.infer<typeof CreateVariantPromotionSchema>;
